config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "about", to: "pages#about"
  
  get "user_profile", to: "users/profiles#show", as: :user_profile
  get "admin_profile", to: "admin/profiles#show", as: :admin_profile

  devise_for :users, controllers: {
    confirmations:      'users/confirmations',
    passwords:          'users/passwords',
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    unlocks:            'users/unlocks'
  }

  devise_for :admins, controllers: {
    confirmations:      'admins/confirmations',
    passwords:          'admins/passwords',
    registrations:      'admins/registrations',
    sessions:           'admins/sessions',
    unlocks:            'admins/unlocks'
  }  
end

app/views/pages/_calculator.html.erb
<div class="calculator">

        <div class="form-group">
            <label for="oamount">Amount:</label>
            <input type="text" class="form-control searchBox" placeholder="0.00" id="oamount">
        </div>

        <br>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">from</span>
            </div>
            <select class="form-control from" id="sel1">
                <option value="">Select currency</option>
                <option value="BRL">BRL</option>
                <option value="EUR">EUR</option>
                <option value="USD">USD</option>
            </select>
        </div>

        <br>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">to</span>
            </div>
            <select class="form-control to" id="sel2">
                <option value="">Select currency</option>
                <option value="BRL">BRL</option>
                <option value="EUR">EUR</option>
                <option value="USD">USD</option>
            </select>
        </div>

        <br>

        <div class="text-center">  
            <button class="btn btn-primary convert m-2" type="submit">Submit</button>
        </div>

        <div id="finalAmount" class="text-center">
            <h2>Exchange result:
                <span class="finalValue" style="color:white;"></span>
            </h2>
        </div>

    </div>
</div>

app/views/pages/about.html.erb
<h1>About Page</h1>
<br>
<p>Ruby on Rails web app that includes a JavaScript currency exchange calculator on the home page.</p>
<br>
<%= link_to "Back", :back, class: 'text-link' %>

app/views/pages/home.html.erb
<div class="main-content">
    
    <div class="sign-up">
        <h1>Forex BR</h1>
        <% if user_signed_in? %>
            <%= link_to "My profile", user_profile_path, class: "btn-primary" %>
        <% elsif admin_signed_in? %>
            <%= link_to "Admin", admin_profile_path, class: "btn-primary" %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn-primary" %>
            <%= link_to "Log in", new_user_session_path, class: "text-link" %>
        <% end %>
        <h3>Currency calculator</h3>
    </div>
    
    <%= render 'calculator' %>
</div>